export { createApp } from './createApp'
export { h } from './h'
export { renderSlots } from './helps/renderSlots'
export { createTextVnode } from './vnode'
export { getCurrentInstance } from './component'
export { provide, inject } from './apiInject'